#include "maglev/gateway/mock_gateway.h"

#include <algorithm>
#include <sstream>

#include "maglev/gateway/gateway_internal.h"
#include "maglev/runtime/util.h"

namespace maglev {

TaskPlanResponse MockGateway::create_task_plan(const std::string&, const std::string& task, const RepositoryContext& repository) {
    TaskPlanResponse response;
    response.summary = "Mock plan for task: " + task;
    response.steps = {
        PlanStep{"read", "Inspect repository " + repository.root_path, "read", false},
        PlanStep{"edit", "Apply generated edits locally", "write_file", true},
        PlanStep{"check", "Run local checks", "run_checks", true},
        PlanStep{"commit", "Create commit", "git_commit", true},
        PlanStep{"push", "Push current branch", "git_push", true},
    };
    return response;
}

std::vector<EditProposal> MockGateway::request_edits(const std::string&, const std::string& task, const RepositoryContext& repository) {
    const auto lowered = to_lower(task);

    if (lowered.find("multiple edits") != std::string::npos || lowered.find("two files") != std::string::npos ||
        lowered.find("несколько файлов") != std::string::npos) {
        return {
            EditProposal{
                "mock-edit-one.md",
                "# Mock Edit One\n\nGenerated by the mock gateway.\n",
                "Create the first mock edit file.",
            },
            EditProposal{
                "mock-edit-two.md",
                "# Mock Edit Two\n\nGenerated by the mock gateway.\n",
                "Create the second mock edit file.",
            },
        };
    }

    if (!repository.attached_files.empty() &&
        (lowered.find("same content") != std::string::npos || lowered.find("same file") != std::string::npos ||
         lowered.find("copy") != std::string::npos || lowered.find("скопиру") != std::string::npos)) {
        std::string target_path = "copied-from-attached.txt";
        const auto create_marker = lowered.find("create a file ");
        if (create_marker != std::string::npos) {
            const auto start = create_marker + std::string("create a file ").size();
            const auto end = lowered.find(' ', start);
            if (end != std::string::npos) {
                target_path = task.substr(start, end - start);
            }
        }

        EditProposal copied_edit;
        copied_edit.path = target_path;
        copied_edit.content = repository.attached_files.front().content;
        copied_edit.summary = "Copy the content of the attached file into a new local file.";
        return {copied_edit};
    }

    EditProposal edit;
    edit.path = "ai-cvsc-output.md";
    edit.content =
        "# AI CVSC Mock Output\n\nTask: " + task + "\n\nThis file was created by the local C++ CLI runtime using the mock gateway.\n";
    edit.summary = "Write a local mock artifact for the requested task.";
    return {edit};
}

CommitMessageProposal MockGateway::request_commit_message(const std::string&, const std::string&, const std::string&) {
    CommitMessageProposal proposal;
    proposal.title = "chore: apply local AI CVSC changes";
    proposal.body = std::string("Generated by the local C++ mock gateway flow.");
    return proposal;
}

DeployRequestProposal MockGateway::request_deploy(
    const std::string&,
    const std::string& instruction,
    const RepositoryContext& repository) {
    std::istringstream stream(instruction);
    std::string segment;
    std::string host = "example-host";
    while (stream >> segment) {
        const bool looks_like_host =
            segment.find('.') != std::string::npos ||
            std::all_of(segment.begin(), segment.end(), [](unsigned char ch) { return std::isdigit(ch); });
        if (looks_like_host) {
            host = segment;
            break;
        }
    }

    DeployRequestProposal proposal;
    proposal.host = host;
    proposal.repo_path = repository.root_path;
    proposal.branch = repository.branch;
    proposal.restart_command = std::string("echo restart service here");
    return proposal;
}

TerminalReply MockGateway::terminal_reply(const std::string&, const std::string& task, const Json& details) {
    const auto mode = details.value("mode", std::string("status"));
    if (mode == "chat" && gateway_detail::is_greeting(task)) {
        return TerminalReply{"Hi. I can chat here, or you can use /task <text> to run the agent workflow."};
    }
    if (mode == "chat") {
        return TerminalReply{"Chat mode: " + task +
                             "\nUse /task <text> when you want planning, edits, checks, commit, push, or deploy."};
    }
    return TerminalReply{"Task '" + task + "': planning complete."};
}

}  // namespace maglev
