use std::collections::BTreeMap;
use std::time::Duration;

use anyhow::{Context, Result, anyhow};
use reqwest::blocking::Client;
use serde::de::DeserializeOwned;
use serde_json::{json, Value};
use uuid::Uuid;

use crate::auth::{build_canonical_request, sign_canonical_request, SigningIdentity};
use crate::config::GatewayConfig;
use crate::contracts::{
    AgentTaskRequest, ChatMessage, CommitMessageProposal, DeployRequestProposal, EditProposal, OpenAiChatRequest,
    OpenAiChatResponse, PlanStep, RepositoryContext, TaskMode, TaskPlanResponse, TerminalReply,
};

pub trait AgentGateway {
    fn create_task_plan(&self, run_id: &str, task: &str, repository: &RepositoryContext) -> Result<TaskPlanResponse>;
    fn request_edits(&self, run_id: &str, task: &str, repository: &RepositoryContext) -> Result<Vec<EditProposal>>;
    fn request_commit_message(&self, run_id: &str, task: &str, diff_summary: &str) -> Result<CommitMessageProposal>;
    fn request_deploy(&self, run_id: &str, instruction: &str, repository: &RepositoryContext) -> Result<DeployRequestProposal>;
    fn terminal_reply(&self, run_id: &str, task: &str, details: Value) -> Result<TerminalReply>;
}

pub struct MockGateway;

impl AgentGateway for MockGateway {
    fn create_task_plan(&self, _run_id: &str, task: &str, repository: &RepositoryContext) -> Result<TaskPlanResponse> {
        Ok(TaskPlanResponse {
            summary: format!("Mock plan for task: {task}"),
            steps: vec![
                PlanStep {
                    id: "read".into(),
                    title: format!("Inspect repository {}", repository.root_path),
                    kind: "read".into(),
                    requires_approval: false,
                },
                PlanStep {
                    id: "edit".into(),
                    title: "Apply generated edits locally".into(),
                    kind: "write_file".into(),
                    requires_approval: true,
                },
                PlanStep {
                    id: "check".into(),
                    title: "Run local checks".into(),
                    kind: "run_checks".into(),
                    requires_approval: true,
                },
                PlanStep {
                    id: "commit".into(),
                    title: "Create commit".into(),
                    kind: "git_commit".into(),
                    requires_approval: true,
                },
                PlanStep {
                    id: "push".into(),
                    title: "Push current branch".into(),
                    kind: "git_push".into(),
                    requires_approval: true,
                },
            ],
        })
    }

    fn request_edits(&self, _run_id: &str, task: &str, _repository: &RepositoryContext) -> Result<Vec<EditProposal>> {
        Ok(vec![EditProposal {
            path: "ai-cvsc-output.md".into(),
            summary: "Write a local mock artifact for the requested task.".into(),
            content: format!(
                "# AI CVSC Mock Output\n\nTask: {task}\n\nThis file was created by the local Rust CLI runtime using the mock gateway.\n"
            ),
        }])
    }

    fn request_commit_message(&self, _run_id: &str, _task: &str, _diff_summary: &str) -> Result<CommitMessageProposal> {
        Ok(CommitMessageProposal {
            title: "chore: apply local AI CVSC changes".into(),
            body: Some("Generated by the local Rust mock gateway flow.".into()),
        })
    }

    fn request_deploy(&self, _run_id: &str, instruction: &str, repository: &RepositoryContext) -> Result<DeployRequestProposal> {
        let host = instruction
            .split_whitespace()
            .find(|segment| segment.contains('.') || segment.chars().all(|char| char.is_ascii_digit()))
            .unwrap_or("example-host")
            .to_string();

        Ok(DeployRequestProposal {
            host,
            repo_path: repository.root_path.clone(),
            branch: repository.branch.clone(),
            restart_command: Some("echo restart service here".into()),
        })
    }

    fn terminal_reply(&self, _run_id: &str, task: &str, _details: Value) -> Result<TerminalReply> {
        Ok(TerminalReply {
            message: format!("Mock gateway accepted task: {task}"),
        })
    }
}

pub struct SecureGateway {
    config: GatewayConfig,
    client: Client,
    identity: SigningIdentity,
}

impl SecureGateway {
    pub fn new(config: GatewayConfig) -> Result<Self> {
        let client = Client::builder()
            .timeout(Duration::from_millis(config.request_timeout_ms))
            .build()
            .context("failed to build HTTP client")?;
        let identity = SigningIdentity::load(&config.private_key_path, config.public_key_path.as_deref())?;
        Ok(Self { config, client, identity })
    }

    fn post<T: DeserializeOwned>(&self, path: &str, payload: AgentTaskRequest) -> Result<T> {
        let url = format!("{}{}", self.config.api_base_url.trim_end_matches('/'), path);
        let body = serde_json::to_string(&payload).context("failed to encode gateway payload")?;
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .context("system clock before unix epoch")?
            .as_millis();
        let nonce = format!("{}-{}", timestamp, Uuid::new_v4());
        let canonical_request = build_canonical_request("POST", path, timestamp, &nonce, &self.identity.key_id, &body);
        let signature = sign_canonical_request(&self.identity, &canonical_request);

        self.client
            .post(url)
            .header("content-type", "application/json")
            .header("x-ai-cvsc-key-id", &self.identity.key_id)
            .header("x-ai-cvsc-timestamp", timestamp.to_string())
            .header("x-ai-cvsc-nonce", &nonce)
            .header("x-ai-cvsc-signature", signature)
            .header("x-ai-cvsc-public-key", &self.identity.public_key_payload)
            .body(body)
            .send()
            .and_then(|response| response.error_for_status())
            .context("gateway request failed")?
            .json::<T>()
            .context("gateway returned invalid JSON")
    }

    fn build_payload(&self, mode: TaskMode, run_id: &str, task: &str, context: Value) -> AgentTaskRequest {
        let mut metadata = BTreeMap::new();
        metadata.insert("model".into(), json!(self.config.model));

        AgentTaskRequest {
            mode,
            run_id: run_id.into(),
            task: task.into(),
            context,
            constraints: None,
            metadata: Some(metadata),
        }
    }
}

impl AgentGateway for SecureGateway {
    fn create_task_plan(&self, run_id: &str, task: &str, repository: &RepositoryContext) -> Result<TaskPlanResponse> {
        self.post("/agent/plan", self.build_payload(TaskMode::TaskPlan, run_id, task, json!(repository)))
    }

    fn request_edits(&self, run_id: &str, task: &str, repository: &RepositoryContext) -> Result<Vec<EditProposal>> {
        self.post("/agent/edits", self.build_payload(TaskMode::EditPatch, run_id, task, json!(repository)))
    }

    fn request_commit_message(&self, run_id: &str, task: &str, diff_summary: &str) -> Result<CommitMessageProposal> {
        self.post(
            "/agent/commit-message",
            self.build_payload(TaskMode::CommitMessage, run_id, task, json!({ "diffSummary": diff_summary })),
        )
    }

    fn request_deploy(&self, run_id: &str, instruction: &str, repository: &RepositoryContext) -> Result<DeployRequestProposal> {
        self.post(
            "/agent/deploy-request",
            self.build_payload(TaskMode::DeployRequest, run_id, instruction, json!(repository)),
        )
    }

    fn terminal_reply(&self, run_id: &str, task: &str, details: Value) -> Result<TerminalReply> {
        self.post(
            "/agent/terminal-reply",
            self.build_payload(TaskMode::TerminalReply, run_id, task, details),
        )
    }
}

pub struct OpenAiCompatGateway {
    config: GatewayConfig,
    client: Client,
}

impl OpenAiCompatGateway {
    pub fn new(config: GatewayConfig) -> Result<Self> {
        let client = Client::builder()
            .timeout(Duration::from_millis(config.request_timeout_ms))
            .build()
            .context("failed to build OpenAI-compatible HTTP client")?;
        Ok(Self { config, client })
    }

    fn chat_json<T: DeserializeOwned>(&self, system_prompt: &str, user_prompt: String) -> Result<T> {
        let url = format!("{}/chat/completions", self.config.api_base_url.trim_end_matches('/'));
        let token_budgets = self.config.openai_json_max_tokens.clone();
        let mut last_error: Option<anyhow::Error> = None;

        for max_tokens in token_budgets {
            let request = OpenAiChatRequest {
                model: self.config.model.clone(),
                messages: vec![
                    ChatMessage {
                        role: "system".into(),
                        content: system_prompt.into(),
                    },
                    ChatMessage {
                        role: "user".into(),
                        content: user_prompt.clone(),
                    },
                ],
                temperature: self.config.openai_temperature,
                max_tokens: Some(max_tokens),
                stream: false,
            };

            let response = self.client
                .post(&url)
                .json(&request)
                .send()
                .and_then(|response| response.error_for_status())
                .context("openai-compatible request failed")?
                .json::<OpenAiChatResponse>()
                .context("openai-compatible endpoint returned invalid JSON")?;

            match parse_json_from_openai_response(&response) {
                Ok(value) => return Ok(value),
                Err(error) => {
                    let should_retry = response
                        .choices
                        .first()
                        .and_then(|choice| choice.finish_reason.as_deref())
                        == Some("length");
                    last_error = Some(error);
                    if !should_retry {
                        break;
                    }
                }
            }
        }

        Err(last_error.unwrap_or_else(|| anyhow!("failed to decode OpenAI-compatible response")))
    }
}

impl AgentGateway for OpenAiCompatGateway {
    fn create_task_plan(&self, _run_id: &str, task: &str, repository: &RepositoryContext) -> Result<TaskPlanResponse> {
        self.chat_json(
            "Return JSON only. Schema: {\"summary\":string,\"steps\":[{\"id\":string,\"title\":string,\"kind\":string,\"requiresApproval\":boolean}]}. No markdown.",
            format!(
                "Create an agent task plan for this task.\nTask: {task}\nRepository context:\n{}",
                serde_json::to_string_pretty(repository).context("failed to serialize repository context")?
            ),
        )
    }

    fn request_edits(&self, _run_id: &str, task: &str, repository: &RepositoryContext) -> Result<Vec<EditProposal>> {
        self.chat_json(
            "Return JSON only. Schema: [{\"path\":string,\"content\":string,\"summary\":string}]. If unsure, create or update a small markdown file that summarizes the requested task. No markdown fences.",
            format!(
                "Propose local file edits for this task.\nTask: {task}\nRepository context:\n{}",
                serde_json::to_string_pretty(repository).context("failed to serialize repository context")?
            ),
        )
    }

    fn request_commit_message(&self, _run_id: &str, task: &str, diff_summary: &str) -> Result<CommitMessageProposal> {
        self.chat_json(
            "Return JSON only. Schema: {\"title\":string,\"body\":string|null}. Keep it short and conventional.",
            format!("Generate a commit message.\nTask: {task}\nDiff summary:\n{diff_summary}"),
        )
    }

    fn request_deploy(&self, _run_id: &str, instruction: &str, repository: &RepositoryContext) -> Result<DeployRequestProposal> {
        self.chat_json(
            "Return JSON only. Schema: {\"host\":string,\"repoPath\":string,\"branch\":string,\"restartCommand\":string|null}. Extract the target host from the instruction if present, otherwise keep the current repository path and branch.",
            format!(
                "Create a deploy request.\nInstruction: {instruction}\nRepository context:\n{}",
                serde_json::to_string_pretty(repository).context("failed to serialize repository context")?
            ),
        )
    }

    fn terminal_reply(&self, _run_id: &str, task: &str, details: Value) -> Result<TerminalReply> {
        self.chat_json(
            "Return JSON only. Schema: {\"message\":string}. The message must be short and terminal-friendly.",
            format!(
                "Summarize the current run state for the terminal.\nTask: {task}\nDetails:\n{}",
                serde_json::to_string_pretty(&details).context("failed to serialize terminal details")?
            ),
        )
    }
}

fn parse_json_from_model_output<T: DeserializeOwned>(content: &str) -> Result<T> {
    let trimmed = content.trim();
    let candidate = if let Some(fenced) = trimmed
        .strip_prefix("```json")
        .and_then(|value| value.strip_suffix("```"))
        .or_else(|| trimmed.strip_prefix("```").and_then(|value| value.strip_suffix("```")))
    {
        fenced.trim()
    } else {
        trimmed
    };

    serde_json::from_str(candidate)
        .or_else(|_| {
            extract_braced_json(candidate)
                .and_then(|json| serde_json::from_str::<T>(&json).ok())
                .ok_or_else(|| serde_json::Error::io(std::io::Error::other("failed to locate JSON object in model output")))
        })
        .context("failed to decode JSON from model output")
}

fn parse_json_from_openai_response<T: DeserializeOwned>(response: &OpenAiChatResponse) -> Result<T> {
    let choice = response
        .choices
        .first()
        .ok_or_else(|| anyhow!("model response did not contain any choices"))?;

    let mut candidates = vec![choice.message.content.as_str()];
    if let Some(reasoning_content) = choice.message.reasoning_content.as_deref() {
        candidates.push(reasoning_content);
    }

    for candidate in candidates {
        if candidate.trim().is_empty() {
            continue;
        }

        if let Ok(value) = parse_json_from_model_output(candidate) {
            return Ok(value);
        }
    }

    Err(anyhow!(
        "failed to decode JSON from content or reasoning_content (finish_reason: {})",
        choice.finish_reason.as_deref().unwrap_or("unknown")
    ))
}

fn extract_braced_json(content: &str) -> Option<String> {
    let first_object = content.find('{').zip(content.rfind('}')).map(|(start, end)| &content[start..=end]);
    if let Some(json) = first_object {
        return Some(json.to_string());
    }

    content.find('[').zip(content.rfind(']')).map(|(start, end)| content[start..=end].to_string())
}
